import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}
      
      <nav>
        <ul>
          <li><Link href='/'>Home</Link></li>
          <li><Link href='/users'>Usuarios</Link></li>
          <li><Link href='/login'>Login</Link></li>
        </ul>
      </nav>
      <hr/>
      
      </body>
    </html>
  )
}
